import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./_components/theme-provider";
import { PixelBlast } from "@/components/PixelBlast";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Envoy CLI | .env versioning made easy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full relative`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <div className="w-full h-full absolute -z-10 hidden dark:block opacity-25">
            <PixelBlast
              variant="circle"
              pixelSize={4}
              color={"#1db6a5"}
              patternScale={5}
              patternDensity={1.5}
              pixelSizeJitter={5}
              speed={0.5}
              edgeFade={0.8}
              enableRipples={true}
              transparent
            />
          </div>
          <div className="w-full h-full absolute -z-10 dark:hidden block opacity-25">
            <PixelBlast
              variant="circle"
              pixelSize={4}
              color={"#1b9388"}
              patternScale={5}
              patternDensity={1.5}
              pixelSizeJitter={5}
              speed={0.5}
              edgeFade={0.8}
              enableRipples={true}
              transparent
            />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
